tasks:
    - init: npm install
      command: npm run start
ports:
    - port: 9229
      onOpen: open-preview
vscode:
    extensions:
        - mikestead.dotenv
        - ms-azuretools.vscode-docker
        - pkief.material-icon-theme
        - ibm.output-colorizer
