name: Version

on:
    workflow_dispatch:
        inputs:
            VERSION:
                description: "Versioning Channels"
                required: true
                default: "master"

jobs:
    version:
        runs-on: ubuntu-latest
        container: node:alpine
        steps:
            - run: apk add openssh-client bash git
            - run: npm i -g semantic-release @semantic-release/git @semantic-release/npm @semantic-release/changelog
            - run: semantic-release -b "$VERSION"
